[build]
  command = "printf 'const CONFIG = { GOOGLE_MAPS_API_KEY: \"%s\", FIREBASE_API_KEY: \"%s\", FIREBASE_AUTH_DOMAIN: \"%s\", FIREBASE_DATABASE_URL: \"%s\", FIREBASE_PROJECT_ID: \"%s\", FIREBASE_APP_ID: \"%s\" };' \"$GOOGLE_MAPS_API_KEY\" \"$FIREBASE_API_KEY\" \"$FIREBASE_AUTH_DOMAIN\" \"$FIREBASE_DATABASE_URL\" \"$FIREBASE_PROJECT_ID\" \"$FIREBASE_APP_ID\" > config.js"
  publish = "."
